### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by xChAmeLIoNz** [mongodb/flask-pymongo#167]
Is this project still maintained?

**Comment by jtazin** [comment]
Hi @xChAmeLIoNz, although this project hasn't been actively worked on recently, I have some good news for you: MongoDB has officially taken over this project, so we will be maintaining it going forward. Stay tuned -- we are planning some updates in the coming months.

We are really grateful to the original creator and maintainer, @dcrosta, who has now kindly handed the project over to us. We're excited to care for Flask-PyMongo and support the MongoDB+Flask dev community at large!

Julia
Product Manager, MongoDB Developer Experience

**Comment by jtazin** [comment]
Hi @xChAmeLIoNz, FYI, we just released version 3.0 of Flask-PyMongo
